### ISSUE TITLE
does not work with web

### ISSUE THREAD

**Issue by ghost** [paivanjerry/simple_autocomplete_search#1]
```
flutter channel beta
flutter upgrade
cd bare_minimum
flutter create .
flutter run -d chrome
```

```
The following NoSuchMethodError was thrown building _BodyBuilder:
'filter'
Dynamic call of null.
Receiver: Instance of 'SimpleAutocompleteSearch'
Arguments: ["No suggestion list entered", ""]
```

**Comment by paivanjerry** [comment]
The issue was a use case when no filtering function was specified. It should now work on web also with version 1.0.5
